import re

# from https://gist.github.com/marijn/274449
COUNTRIES = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "American Samoa",
    "Andorra",
    "Angola",
    "Anguilla",
    "Antarctica",
    "Antigua And Barbuda",
    "Argentina",
    "Armenia",
    "Aruba",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bermuda",
    "Bhutan",
    "Bolivia",
    "Bosnia And Herzegovina",
    "Botswana",
    "Bouvet Island",
    "Brazil",
    "British Indian Ocean Territory",
    "Brunei Darussalam",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cape Verde",
    "Cayman Islands",
    "Central African Republic",
    "Chad",
    "Chile",
    "China, People's Republic Of",
    "Christmas Island",
    "Cocos (Keeling) Islands",
    "Colombia",
    "Comoros",
    "Congo",
    "Congo, The Democratic Republic Of The",
    "Cook Islands",
    "Costa Rica",
    "Cote D'ivoire",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "East Timor",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Ethiopia",
    "Falkland Islands (Malvinas)",
    "Faroe Islands",
    "Fiji",
    "Finland",
    "France",
    "French Guiana",
    "French Polynesia",
    "French Southern Territories",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Gibraltar",
    "Greece",
    "Greenland",
    "Grenada",
    "Guadeloupe",
    "Guam",
    "Guatemala",
    "Guinea",
    "Guinea-bissau",
    "Guyana",
    "Haiti",
    "Heard Island And Mcdonald Islands",
    "Holy See (Vatican City State)",
    "Honduras",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran, Islamic Republic Of",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakstan",
    "Kenya",
    "Kiribati",
    "Korea, Democratic People's Republic Of",
    "Korea, Republic Of",
    "Kosovo",
    "Kuwait",
    "Kyrgyzstan",
    "Lao People's Democratic Republic",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libyan Arab Jamahiriya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macau",
    "Macedonia, The Former Yugoslav Republic Of",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Martinique",
    "Mauritania",
    "Mauritius",
    "Mayotte",
    "Mexico",
    "Micronesia, Federated States Of",
    "Moldova, Republic Of",
    "Monaco",
    "Mongolia",
    "Montserrat",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "Netherlands Antilles",
    "New Caledonia",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Niue",
    "Norfolk Island",
    "Northern Mariana Islands",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestinian Territory, Occupied",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Pitcairn",
    "Poland",
    "Portugal",
    "Puerto Rico",
    "Qatar",
    "Reunion",
    "Romania",
    "Russian Federation",
    "Rwanda",
    "Saint Helena",
    "Saint Kitts And Nevis",
    "Saint Lucia",
    "Saint Pierre And Miquelon",
    "Saint Vincent And The Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome And Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Georgia And The South Sandwich Islands",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Svalbard And Jan Mayen",
    "Swaziland",
    "Sweden",
    "Switzerland",
    "Syrian Arab Republic",
    "Taiwan, Province Of China",
    "Tajikistan",
    "Tanzania, United Republic Of",
    "Thailand",
    "Togo",
    "Tokelau",
    "Tonga",
    "Trinidad And Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Turks And Caicos Islands",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "United States Minor Outlying Islands",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Venezuela",
    "Viet Nam",
    "Virgin Islands, British",
    "Virgin Islands, U.s.",
    "Wallis And Futuna",
    "Western Sahara",
    "Yemen",
    "Zambia",
    "Zimbabwe",
]

# Additions
# - countries that are often used in truncated or abbreviated form
COUNTRIES.extend(
    [
        "Bosnia",
        "China",
        "Congo",
        "Guinea",
        "Vatican",
        "Iran",
        "Korea",
        "North Korea",
        "South Korea",
        "Macedonia",
        "Micronesia",
        "Moldova",
        "Palestine",
        "Palestinian Territory",
        "Russia",
        "South Georgia",
        "Syria",
        "Taiwan",
        "Tanzania",
        "Vietnam",
        "Virgin Islands",
    ]
)
# - rearranged strings of countries with extended names (removing commas)
COUNTRIES.extend(
    [
        "People's Republic of China",
        "Democratic Republic of the Congo",
        "Islamic Republic of Iran",
        "Democratic People's Republic of Korea",
        "Republic of Korea",
        "Former Yugoslav Republic of Macedonia",
        "Federated States of Micronesia",
        "Republic of Moldova",
        "Occupied Palestinian Territory",
        "United Republic of Tanzania",
        "British Virgin Islands",
        "U.S. Virgin Islands",
    ]
)

# from https://gist.github.com/marijn/274449
NATIONALITIES = [
    "Afghan",
    "Albanian",
    "Algerian",
    "American",
    "Andorran",
    "Angolan",
    "Antiguans",
    "Argentinean",
    "Armenian",
    "Australian",
    "Austrian",
    "Azerbaijani",
    "Bahamian",
    "Bahraini",
    "Bangladeshi",
    "Barbadian",
    "Barbudans",
    "Batswana",
    "Belarusian",
    "Belgian",
    "Belizean",
    "Beninese",
    "Bhutanese",
    "Bolivian",
    "Bosnian",
    "Brazilian",
    "British",
    "Bruneian",
    "Bulgarian",
    "Burkinabe",
    "Burmese",
    "Burundian",
    "Cambodian",
    "Cameroonian",
    "Canadian",
    "Cape Verdean",
    "Central African",
    "Chadian",
    "Chilean",
    "Chinese",
    "Colombian",
    "Comoran",
    "Congolese",
    "Costa Rican",
    "Croatian",
    "Cuban",
    "Cypriot",
    "Czech",
    "Danish",
    "Djibouti",
    "Dominican",
    "Dutch",
    "East Timorese",
    "Ecuadorean",
    "Egyptian",
    "Emirian",
    "Equatorial Guinean",
    "Eritrean",
    "Estonian",
    "Ethiopian",
    "Fijian",
    "Filipino",
    "Finnish",
    "French",
    "Gabonese",
    "Gambian",
    "Georgian",
    "German",
    "Ghanaian",
    "Greek",
    "Grenadian",
    "Guatemalan",
    "Guinea-Bissauan",
    "Guinean",
    "Guyanese",
    "Haitian",
    "Herzegovinian",
    "Honduran",
    "Hungarian",
    "I-Kiribati",
    "Icelander",
    "Indian",
    "Indonesian",
    "Iranian",
    "Iraqi",
    "Irish",
    "Israeli",
    "Italian",
    "Ivorian",
    "Jamaican",
    "Japanese",
    "Jordanian",
    "Kazakhstani",
    "Kenyan",
    "Kittian and Nevisian",
    "Kuwaiti",
    "Kyrgyz",
    "Laotian",
    "Latvian",
    "Lebanese",
    "Liberian",
    "Libyan",
    "Liechtensteiner",
    "Lithuanian",
    "Luxembourger",
    "Macedonian",
    "Malagasy",
    "Malawian",
    "Malaysian",
    "Maldivian",
    "Malian",
    "Maltese",
    "Marshallese",
    "Mauritanian",
    "Mauritian",
    "Mexican",
    "Micronesian",
    "Moldovan",
    "Monacan",
    "Mongolian",
    "Moroccan",
    "Mosotho",
    "Motswana",
    "Mozambican",
    "Namibian",
    "Nauruan",
    "Nepalese",
    "New Zealander",
    "Ni-Vanuatu",
    "Nicaraguan",
    "Nigerian",
    "Nigerien",
    "North Korean",
    "Northern Irish",
    "Norwegian",
    "Omani",
    "Pakistani",
    "Palauan",
    "Panamanian",
    "Papua New Guinean",
    "Paraguayan",
    "Peruvian",
    "Polish",
    "Portuguese",
    "Qatari",
    "Romanian",
    "Russian",
    "Rwandan",
    "Saint Lucian",
    "Salvadoran",
    "Samoan",
    "San Marinese",
    "Sao Tomean",
    "Saudi",
    "Scottish",
    "Senegalese",
    "Serbian",
    "Seychellois",
    "Sierra Leonean",
    "Singaporean",
    "Slovakian",
    "Slovenian",
    "Solomon Islander",
    "Somali",
    "South African",
    "South Korean",
    "Spanish",
    "Sri Lankan",
    "Sudanese",
    "Surinamer",
    "Swazi",
    "Swedish",
    "Swiss",
    "Syrian",
    "Taiwanese",
    "Tajik",
    "Tanzanian",
    "Thai",
    "Togolese",
    "Tongan",
    "Trinidadian or Tobagonian",
    "Tunisian",
    "Turkish",
    "Tuvaluan",
    "Ugandan",
    "Ukrainian",
    "Uruguayan",
    "Uzbekistani",
    "Venezuelan",
    "Vietnamese",
    "Welsh",
    "Yemenite",
    "Zambian",
    "Zimbabwea",
]

# Random additions that don't appear in the above list
NATIONALITIES.extend(
    ["English", "Jewish", "Korean", "Kurdish", "Persian", "Puerto Rican", "Philippine"]
)

# from https://en.wikipedia.org/wiki/List_of_languages_by_number_of_native_speakers
LANGUAGES = [
    "Chinese",
    "Mandarin",
    "Spanish",
    "English",
    "Hindi",
    "Arabic",
    "Bengali",
    "Portuguese",
    "Russian",
    "Japanese",
    "Lahnda",
    "Western Punjabi",
    "Marathi",
    "Telugu",
    "Wu",
    "Malay",
    "Turkish",
    "Korean",
    "French",
    "German",
    "Vietnamese",
    "Tamil",
    "Yue",
    "Urdu",
    "Javanese",
    "Italian",
    "Egyptian",
    "Persian",
    "Gujarati",
    "Iranian Persian",
    "Bhojpuri",
    "Min Nan",
    "Hakka",
    "Jinyu",
    "Hausa",
    "Kannada",
    "Indonesian",
    "Polish",
    "Pushto",
    "Yoruba",
    "Xiang Chinese",
    "Malayalam",
    "Oriya",
    "Odia",
    "Maithili",
    "Burmese",
    "Eastern Punjabi",
    "Sudanese",
    "Fulah",
    "Uzbek",
    "Algerian",
    "Moroccan",
    "Ukrainian",
    "Igbo",
    "Northern Uzbek",
    "Sindhi",
    "North Levantine",
    "Romanian",
    "Tagalog",
    "Dutch",
    "Azerbaijani",
    "Sa Ωidi",
    "Kurdish",
    "Gan",
    "Amharic",
    "Northern Pashto",
    "Magahi",
    "Thai",
    "Marwari",
    "Saraiki",
    "Malagasy",
    "Oromo",
    "Serbo-Croatian",
    "Khmer",
    "Chhattisgarhi",
    "Somali",
    "Malay",
    "Cebuano",
    "Nepali",
    "Mesopotamian",
    "Assamese",
    "Sinhala",
    "Zhuang",
    "Northern Kurdish",
    "Hijazi",
    "Nigerian Fulfulde",
    "South Azerbaijani",
    "Greek",
    "Chittagonian",
    "Kazakh",
    "Deccan",
    "Hungarian",
    "Kinyarwanda",
    "Zulu",
    "South Levantine",
    "Tunisian",
    "Sanaani",
    "Min Bei Chinese",
    "Southern Pashto",
    "Rundi",
    "Czech",
    "Ta Ωizzi-Adeni",
    "Uyghur",
    "Min Dong Chinese",
    "Sylheti",
    "Baluchi",
]

LANGUAGES.extend(["Levantine", "Pashto", "Fula", "Min Bei", "Cantonese"])

# Words that describe a race outside of an ethnicity
RACE_WORDS = {
    "african american",
    "african",
    "hispanic",
    "latin",
    "latino",
    "latina",
    "latinx",
    "asian",
    "native american",
    "indigenous",
}
# Adds "-american" and "american" to RACE_WORDS that lack them
RACE_WORDS.update(
    [
        f"{race_word} american"
        for race_word in RACE_WORDS
        if re.search("american", race_word) is None
    ]
)
RACE_WORDS.update(
    [
        f"{race_word}-american"
        for race_word in RACE_WORDS
        if re.search("american", race_word) is None
    ]
)

# Race abbreviation options:
# - Race: A = Asian, B = Black, H = Hispanic, O = Oriental, PI = Pacific Islander, W = White
# - Gender: F = Female, M = Male
# - Age: A = Adult, J = Juvenile
RACE_ABBREV = "([ABHOW]|PI)(F|M)(A|J)"

WEB_COLORS = [
    "#FF0000",
    "#0000FF",
    "#008000",
    "#FFA500",
    "#800080",
    "#FF00FF",
    "#C0C0C0",
    "#A52A2A",
    "#800000",
    "#808000",
]

# TODO: foresee issue of abbreviated skin colors e.g. BLK (black), BLN (blonde), BRN (brown)
SKIN_COLORS = {"black", "white", "brown", "latin", "dark", "pale", "light"}

PERSON_REF = {
    "boy",
    "boys",
    "man",
    "men",
    "male",
    "males",
    "gentleman",
    "gentlemen",
    "girl",
    "girls",
    "woman",
    "women",
    "female",
    "females",
    "lady",
    "ladies",
    "person",
    "persons",
    "people",
    "kid",
    "kids",
    "child",
    "children",
    "adult",
    "adults",
    "complexion",
    "guy",
}

HAIR_COLORS = {
    "black",
    "white",
    "gray",
    "grey",
    "brown",
    "bald",
    "balding",
    "brunette",
    "blond",
    "blonde",
    "red",
    "orange",
    "auburn",
    "platinum",
    "ombre",
    "strawberry blond",
    "strawberry blonde",
    "salt and pepper",
    "salt & pepper",
    "bleached",
    "dyed",
    "light",
    "dark",
    "silver",
}


# Terms related to hair that might convey race and should be redacted
SENSITIVE_HAIR_REF = {
    "dreadlocks",
    "dread locks",
    "dread-locks",
    "cornrows",
    "corn rows",
    "corn-rows",
    "afro",
    "nappy",
}

# Terms used to indicate that we're discussing hair.
# See also SENSITIVE_HAIR_REF.
HAIR_REF = {
    "hair",
    "haircut",
    "hairstyle",
    "hair style",
    "hairdo",
    "moustache",
    "beard",
    "goatee",
    "sideburns",
    "mullet",
    "bun",
    "ponytail",
    "pony tail",
    "braids",
    "mohawk",
    "fade",
    "crew cut",
} | SENSITIVE_HAIR_REF

# Adjectives that are often used to describe hair
HAIR_ADJS = {
    "short",
    "curly",
    "long",
    "wavy",
    "shaggy",
    "matted",
    "frizzy",
    "scraggly",
    "shoulder-length",
    "shoulder length",
    "straight",
    "wiry",
    "spiky",
    "bushy",
    "close cropped",
    "close-cropped",
    "cropped",
    "style",
    "type",
}

EYE_COLORS = {
    "gray",
    "grey",
    "blue",
    "light blue",
    "green",
    "hazel",
    "black",
    "brown",
    "pink",
}

EYE_REF = {
    "eye",
    "eyes",
}

# Features correlated with race that are always redacted
RACE_FEATURES = {
    "latin",
    "brunette",
    "blond",
    "blonde",
}

GENERAL_COLORS = {
    "black",
    "white",
    "gray",
    "grey",
    "red",
    "red-orange",
    "red orange",
    "orange-red",
    "orange red",
    "orange",
    "yellow",
    "green",
    "blue",
    "indigo",
    "turquoise",
    "violet",
    "purple",
    "pink",
    "magenta",
    "amber",
}

APPEARANCE_LIST = {"race", "complexion", "eyes", "hair"}

NAME_PHRASES = {
    "name of",
    "named",
    "name",
    "brother",
    "sister",
    "father",
    "mother",
    "dad",
    "mom",
    "female",
    "male",
    "girlfriend",
    "boyfriend",
    "wife",
    "husband",
    "friend",
}